### ISSUE TITLE
[Lab2_Dev]Добавит скрипты создания таблиц

### ISSUE THREAD

**Issue by avchirkov91** [DmitryPimuhskin/O21_NC#19]
Создать скрипт для создания таблиц в базе данных
/database/script.sql

P.S. Создание таблиц с PK без FK

**Comment by DmitryPimuhskin** [comment]
Выполнено

**Comment by avchirkov91** [comment]
Таблицы Model не будет - в 1 лабе это была БД))

Правила именования таблиц (неофицально)
1. Имя таблицы: название сущности во мн. числе и большими буквами 
2. Пробелы пишем в виде "_"
3. Для таблиц связи многие ко многим СУЩНОСТЬ1_СУЩНОСТЬ2 в ед.числе

+ куча лишней инфы и недостаточно цельная БД (я не брал в расчет FK)

**Comment by avchirkov91** [comment]
Соблюдайте нейминг описанный выше

**Comment by avchirkov91** [comment]
Исправить поля на верхний регистр

**Comment by avchirkov91** [comment]
Переименовать таблице в USERS_LIB в USERS
Убрать добавление Fk при создании таблиц
пересмотреть первичный ключ для PUBLICATION_AUTHOR,BOOK_PUBLICATION

**Comment by avchirkov91** [comment]
по FK создал отдельную задачу
принято
